### ISSUE TITLE
SD card footprint mirrored?

### ISSUE THREAD

**Issue by RolandJuno** [alexthecat123/ArduinoFile#4]
I ordered some boards of the ArduinoFile 1.1 gerbers (labeled v4 on the schematic-- with P0-7 pins mapped to A0-A7) and noticed the SD card pinout might be reversed from the original. The SD card reader needs to be installed up sidedown.

Edit: I also think the pin mapping for the LED needs to be changed as below.

```
const int red = 41; // was 22
const int green = 40; // was 23
const int blue = 39;  // 24
```

```
  //pinMode(22, OUTPUT); // old pin assignments
  //pinMode(23, OUTPUT);
  //pinMode(24, OUTPUT);
  pinMode(red, OUTPUT); // new pin assignments
  pinMode(green, OUTPUT);
  pinMode(blue, OUTPUT);
```

With these changes, the ArduinoFile boards seem to be functional! Cheers!

**Comment by i-to-z** [comment]
Interesting.
I just received today 5 new boards from JLpcb and did a continuity test with a multimeter.
I confirm that @RolandJuno is correct about the SD card and the LED.

I personally welcome the SD card change because the SD card adapters that I bught have pins soldered on the side of the card holder; for the older board I had to desolder them to move them to the other side, now I don't have to.

**Comment by alexthecat123** [comment]
Yeah, you're totally right about the SD card and LED issues! I guess that's what I get for making modifications to the PCB without actually ordering and testing them. Sorry about all that! I've updated the PCB to fix the SD card issue as well as the code to fix the LED issue, so we should be good to go now!
